### ISSUE TITLE
The steps component hopes to support multi-level headings.

### ISSUE THREAD

**Issue by duxphp** [ZTL-UwU/shadcn-docs-nuxt#17]
When the steps component uses h4 as the title, it cannot be parsed. It is hoped that the highest-level title within the component can be automatically used as the step title.

**Comment by ZTL-UwU** [comment]
It is not easy to scan everything in the default slot, and I want to keep it css only. So instead I added a prop to the `steps` component. You can define what level heading to use with `::steps{level=x}`.

Fixed in [70cde1a](https://github.com/ZTL-UwU/shadcn-docs-nuxt/commit/70cde1a4ccad2af99ca9cd9aa3fb27dc4a48ad79)
