### ISSUE TITLE
Confusion about the layout of the Aside section

### ISSUE THREAD

**Issue by peoray** [ZTL-UwU/shadcn-docs-nuxt#36]
I'm confused on how the aside is designed. From the  default design, it seems that the top section controls the bottom section like so:
<img width="354" alt="Screenshot 2024-10-09 at 2 15 14 AM" src="https://github.com/user-attachments/assets/6d2f0334-efd8-4ba4-b14a-280c63876c91">

What if I want it to be each own section like so:
<img width="287" alt="Screenshot 2024-10-09 at 2 16 49 AM" src="https://github.com/user-attachments/assets/866faaf5-f224-44d6-8d88-f9430aac090e">

And then, can the breadcrumbs be from the file path? My path is `/docs/{anything}`, and I want the breadcrumbs to be `Docs > {anything}`. So basically, I want the breadcrumbs in all the pages of `/docs/{anything}`.

**Comment by ZTL-UwU** [comment]
> I'm confused on how the aside is designed. From the default design, it seems that the top section controls the bottom section like so:

You can set `useLevel` to `false` in https://shadcn-docs.nuxt.dev/api/configuration/shadcn-docs#aside.

> And then, can the breadcrumbs be from the file path? My path is /docs/{anything}, and I want the breadcrumbs to be Docs > {anything}. So basically, I want the breadcrumbs in all the pages of /docs/{anything}.

The breadcrumbs are based on url paths instead of file paths. If you want all to start with `Docs`, you can override the [Breadcrumb Component](https://shadcn-docs.nuxt.dev/api/advanced/override) (`/components/layout/Breadcrumb.vue`)

**Comment by peoray** [comment]
Thanks.

Figured the useLevel flag. I'll look into the breadcrumb component
